### ISSUE TITLE
Adopting music21j to the generated code from music21.vexflow.toMusic21j.py

### ISSUE THREAD

**Issue by jongwon-park** [cuthbertLab/music21j#13] opened 2015-10-12 13:46 UTC
Hello.

I got a problem when adopting music21j to the generated code from music21.vexflow.toMusic21j.py

I run the bellow code using music21.

> > > n = note.Note('C#4')
> > > print(vexflow.toMusic21j.fromObject(n, mode='jsbody'))

Then, I got the bellow code.

require(['music21'], function() {
                var pickleIn = '{"m21Version": {"py/tuple": [2, 1, 2]}, "stream": {"py/object": "music21.stream.Stream", "py/state": {"_mutabl' + 
    'e": true, "_activeSite": null, "xPosition": null, "_priority": 0, "_elements": [], "_cache": {}, "definesExpli' + 
    'citPageBreaks": false, "_unlinkedDuration": null, "id": 140225177544656, "_duration": null, "_offsetDict": {},' + 
    ' "streamStatus": {"py/object": "music21.stream.streamStatus.StreamStatus", "py/state": {"_enharmonics": null, ' + 
    '"_dirty": null, "_concertPitch": null, "_accidentals": null, "_ties": null, "_rests": null, "_ornaments": null' + 
    ', "_client": null, "_beams": null, "_measures": null}}, "sites": {"py/object": "music21.sites.Sites", "py/stat' + 
    'e": {"siteDict": {}, "_lastID": -1, "_siteIndex": 0}}, "isFlat": true, "autoSort": true, "_storedElementOffset' + 
    'Tuples": [{"py/tuple": [{"py/object": "music21.note.Note", "py/state": {"lyrics": [], "_notehead": "normal", "' + 
    '_volume": null, "_activeSite": null, "xPosition": null, "_priority": 0, "pitch": {"py/object": "music21.pitch.' + 
    'Pitch", "_groups": null, "_overridden_freq440": null, "_step": "C", "_octave": 4, "_microtone": {"py/object": ' + 
    '"music21.pitch.Microtone", "py/state": {"_harmonicShift": 1, "_centShift": 0}}, "_accidental": {"py/object": "' + 
    'music21.pitch.Accidental", "py/state": {"_modifier": "#", "_alter": 1.0, "displayLocation": "normal", "_displa' + 
    'yType": "normal", "displaySize": "full", "_name": "sharp", "_displayStatus": null, "displayStyle": "normal"}},' + 
    ' "fundamental": null, "defaultOctave": 4, "implicitAccidental": false}, "expressions": [], "id": 1402251775445' + 
    '92, "_duration": {"py/object": "music21.duration.Duration", "py/state": {"_componentsNeedUpdating": true, "_tu' + 
    'plets": {"py/tuple": []}, "_qtrLength": 1.0, "_linked": true, "_components": [], "_dotGroups": {"py/tuple": [0' + 
    ']}, "_client": {"py/id": 4}, "_unlinkedType": null, "_quarterLengthNeedsUpdating": false, "_typeNeedsUpdating"' + 
    ': false}}, "_noteheadParenthesis": false, "sites": {"py/object": "music21.sites.Sites", "py/state": {"siteDict' + 
    '": {}, "_lastID": -1, "_siteIndex": 4}}, "_editorial": null, "tie": null, "_noteheadFill": null, "beams": {"py' + 
    '/object": "music21.beam.Beams", "py/state": {"feathered": false, "beamsList": []}}, "_naiveOffset": 0.0, "grou' + 
    'ps": {"py/object": "music21.base.Groups", "py/seq": []}, "linkage": "tie", "articulations": [], "hideObjectOnP' + 
    'rint": false, "_activeSiteStoredOffset": null, "_stemDirection": "unspecified", "_derivation": null}}, 0.0]}],' + 
    ' "_derivation": null, "_naiveOffset": 0.0, "groups": {"py/object": "music21.base.Groups", "py/seq": []}, "isSo' + 
    'rted": false, "hideObjectOnPrint": false, "_activeSiteStoredOffset": null, "_endElements": [], "_atSoundingPit' + 
    'ch": "unknown", "definesExplicitSystemBreaks": false}}}';
                var jpc = new music21.jsonPickle.Converter();
                streamObj = jpc.run(pickleIn);
                streamObj.renderOptions.events.resize = "reflow";
                streamObj.appendNewCanvas();
            });

I made the test html file using the code. and I run the code on music21j.
% cd $MUSIC21J_HOME
% python start_python_server.py

On browser(Crome)
http://localhost:8000/testHTML/test.html

Finally, I got the error.

M21object without classes:  Object {_activeSite: null, _activeSiteStoredOffset: null, _derivation: null, _duration: Object, _editorial: null…}
fromPython.js:137 Uncaught TypeError: s.append is not a function

I compared the jsonpickleParse.html of example and the generated code from music21.
The format of pickleIn is different.

**Comment by mscuthbert** [comment] 2015-10-12 14:30
It looks like the code changes in v.2. produce output that is slightly different than before.  I'll look into it.  It might be a week or so.

**Comment by cyrrill** [comment] 2015-12-05 02:02
I can confirm this issue:

The << s.append is a not a function >> error seems to appear as a direct consequence of a previous warning

```
M21object without classes:  
Object {py/object: "music21.metadata.Metadata", py/state: Object, _py_class: "music21.metadata.Metadata", offset: 0}
```

Which happens because 
```
var classList = el._classes;
```
is empty.


Any suggestions on workarounds while the core issue is being worked on?

**Comment by calpeyser** [comment] 2016-02-14 20:53
I've got the same issue, and could certainly use a workaround.  I'm also happy to help contribute a solution, if I can get some guidance as to what the problem is.

**Comment by infojunkie** [comment] 2016-07-02 21:46
As far as I can understand, the format that is generated by Python's `music21.ext.jsonpickle.Pickler` is not compatible with the format that is expected by JavaScript's `ext/jsonpickle/unpickler`. I expect they drifted out of sync and that the Python one is more current.

Since the Python unpickler (`music21.ext.jsonpickle.Unpickler`) seems to be working correctly, I am trying to make the JS implementation of the unpickler work like the Python one.

**Comment by mscuthbert** [comment] 2016-07-03 00:13
If it's a jsonpickle to JsonpickleJS problem that doesn't have anything to do w/ music21, better to suggest a patch on https://github.com/cuthbertLab/jsonpickleJS and then when that's fixed we can merge here.

**Comment by infojunkie** [comment] 2016-07-03 00:32
Sure, I will do that once I get it to work :-)

**Comment by infojunkie** [comment] 2016-07-03 17:22
Submitted a PR to jsonpickleJS to fix simple cases, e.g. unpickling a `chord.Chord("C4 E4- G4")`. The more general case of unpickling a full score like `corpus.parse('bach/bwv66.6')` is still broken, I'll be working on that.

**Comment by MickyDowns** [comment] 2016-10-17 00:18
So, what is the best way to get music21 scores into music21j?

This thread seems to suggest jsonpickleJS won't work, though I don't see an issue on https://github.com/cuthbertLab/jsonpickleJS/issues.

Right now I'm streaming in (via socketio) tiny notation. However, I don't see a m21 -> tiny converter suggesting I'd need to reverse engineer the tiny -> m21 converter for scale.

Is that right? Or am I missing something basic?

**Comment by mscuthbert** [comment] 2016-10-29 19:56
At this point it is still through the jsonpickleJS interface.  Do the pull requests merged here still leave problems?

**Comment by mscuthbert** [comment] 2017-09-15 22:04
(MusicXML import is almost ready; a few more bugs...)

Closing this -- reopen if it's still an issue.

**Closed by mscuthbert** 2017-09-15 22:04 UTC
